name: "Setup OpenCV Static"
description: "Setup OpenCV Static"
author: "Nilesh Mali"
inputs:
  opencv-version:
    description: "OpenCV version to be installed."
  opencv-contrib:
    description: "If opencv-contrib (extra modules) should be included in the installation."
    default: "true"
  github-token:
    description: "GitHub token to be used for downloading releases."
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
